# explicit commands for building the site
# and the folder to publish
[build]
command = "bundle exec jekyll build"
publish = "_site"

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[plugins]]
# runs Cypress tests against the deployed URL
    package = "netlify-plugin-cypress"
    [plugins.inputs]
        record = true